In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

import os
import gc

  
df = pd.read_csv("/content/drive/MyDrive/Team 55 [NEW]/Data/zillow_data_update/zillow_all_homes.csv")
#drop useless columns: RegionID, RegionType, StateName, State, Metro, StateCodeFIPS, MunicipalCodeFIPS, tier
df.drop(columns=["RegionID", "RegionType", "StateName", "State", "Metro", "StateCodeFIPS", "MunicipalCodeFIPS", "tier"], inplace=True)
keyCounty = ["Washington Parish", "Orleans Parish", "St. Bernard Parish", "St. Charles Parish", "Jefferson Parish", "Plaquemines Parish", "St. James Parish", "St. John the Baptist Parish", "St. Tammany Parish", "Tangipahoa Parish", "Ascension Parish", "East Baton Rouge Parish", "East Feliciana Parish", "Iberville Parish", "Livingston Parish", "Pointe Coupee Parish", "St. Helena Parish", "West Baton Rouge Parish", "West Feliciana Parish", "Caddo Parish"]
df = df.loc[df['RegionName'].isin(keyCounty)]

#break up dataframe into years and then find the median values for those parishes by the years
df["Date"] = pd.to_datetime(df["Date"])
year = 2000 
df_list = []

while year < 2021:
    df_filtered = df.loc[df.Date.dt.year == year]
    df_list.append(df_filtered)
    year += 1

year_median_df_list = []
#find the meadian of each year
for df in df_list:
    year_median_df_list.append(df.groupby('RegionName').median())

def combineLists(df_list):
    # Set the initial dataframe to merge
    result = df_list[0]
    year = 2000
    # Loop through the remaining dataframes and merge them one by one
    for i in range(1, len(df_list)):
        old_year = '_'+ str(year)
        year += 1
        new_year = '_'+ str(year)
        result = pd.merge(left=result, right=df_list[i], on='RegionName', suffixes=[old_year, new_year])
    column_names = {'SizeRank':'SizeRank_2020','Value':'Value_2020'}
    result = result.rename(columns = column_names)
    return result

median_house_df = combineLists(year_median_df_list)
median_house_df

,SizeRank_2000,Value_2000,SizeRank_2001,Value_2001,SizeRank_2002,Value_2002,SizeRank_2003,Value_2003,SizeRank_2004,Value_2004,...,SizeRank_2016,Value_2016,SizeRank_2017,Value_2017,SizeRank_2018,Value_2018,SizeRank_2019,Value_2019,SizeRank_2020,Value_2020
RegionName,,,,,,,,,,,,,,,,,,,,,
Ascension Parish,514.0,NaN,514.0,NaN,514.0,NaN,514.0,NaN,514.0,NaN,...,514.0,214476.5,514.0,223076.0,514.0,225603.5,514.0,222889.5,514.0,229958.0
Caddo Parish,274.0,NaN,274.0,NaN,274.0,NaN,274.0,NaN,274.0,NaN,...,274.0,113063.5,274.0,115445.5,274.0,115637.5,274.0,113678.0,274.0,117873.0
East Baton Rouge Parish,158.0,NaN,158.0,NaN,158.0,140544.0,158.0,137937.0,158.0,141442.5,...,158.0,176484.5,158.0,178861.5,158.0,190521.0,158.0,185271.5,158.0,188895.0
East Feliciana Parish,1858.0,NaN,1858.0,NaN,1858.0,NaN,1858.0,NaN,1858.0,NaN,...,1858.0,123927.5,1858.0,132435.0,1858.0,143776.5,1858.0,148747.0,1858.0,153171.0
Iberville Parish,1360.0,NaN,1360.0,NaN,1360.0,NaN,1360.0,NaN,1360.0,NaN,...,1360.0,159060.5,1360.0,163058.0,1360.0,165624.5,1360.0,169499.0,1360.0,171098.0
Jefferson Parish,160.0,154157.0,160.0,161700.0,160.0,168431.5,160.0,173647.5,160.0,173796.0,...,160.0,188667.0,160.0,196755.5,160.0,203917.0,160.0,209231.5,160.0,219893.5
Livingston Parish,462.0,NaN,462.0,NaN,462.0,NaN,462.0,NaN,462.0,NaN,...,462.0,165382.0,462.0,167725.0,462.0,177946.0,462.0,176038.5,462.0,182258.0
Orleans Parish,178.0,129889.5,178.0,141408.5,178.0,147275.0,178.0,157153.5,178.0,171080.5,...,178.0,211892.5,178.0,212783.0,178.0,215503.0,178.0,212697.5,178.0,237303.0
Plaquemines Parish,1661.0,NaN,1661.0,NaN,1661.0,196522.0,1661.0,204837.0,1661.0,218556.5,...,1661.0,276786.0,1661.0,282278.5,1661.0,285267.0,1661.0,294380.5,1661.0,300382.5
Pointe Coupee Parish,1725.0,NaN,1725.0,NaN,1725.0,NaN,1725.0,NaN,1725.0,NaN,...,1725.0,183006.0,1725.0,187969.0,1725.0,191281.5,1725.0,197161.5,1725.0,201110.5
Tangipahoa Parish,484.0,NaN,484.0,NaN,484.0,NaN,484.0,NaN,484.0,NaN,...,484.0,158711.0,484.0,163597.0,484.0,162381.0,484.0,162653.5,484.0,169170.0
Washington Parish,1041.0,NaN,1041.0,NaN,1041.0,NaN,1041.0,NaN,1041.0,NaN,...,1041.0,104881.0,1041.0,108190.0,1041.0,107060.0,1041.0,110754.0,1041.0,114661.5
West Baton Rouge Parish,1560.0,NaN,1560.0,NaN,1560.0,NaN,1560.0,NaN,1560.0,NaN,...,1560.0,184359.5,1560.0,190905.5,1560.0,192520.5,1560.0,199239.5,1560.0,203132.5
West Feliciana Parish,2071.0,NaN,2071.0,NaN,2071.0,NaN,2071.0,NaN,2071.0,NaN,...,2071.0,229289.5,2071.0,234873.5,2071.0,242941.5,2071.0,248207.0,2071.0,250268.0

**From year 2000 to 2010 there is missing data for the years**

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Team 55 [NEW]/Data/zillow_data_update/zillow_bdrmcnt.csv")
df

,RegionID,SizeRank,RegionName,RegionType,StateName,State,Metro,StateCodeFIPS,MunicipalCodeFIPS,Date,Value,bdrmcnt
0,3266,158,East Baton Rouge Parish,county,LA,LA,"Baton Rouge, LA",22,33,2000-01-31,NaN,0
1,2743,160,Jefferson Parish,county,LA,LA,"New Orleans-Metairie, LA",22,51,2000-01-31,NaN,0
2,1953,178,Orleans Parish,county,LA,LA,"New Orleans-Metairie, LA",22,71,2000-01-31,156952.0,0
3,3225,265,Saint Tammany Parish,county,LA,LA,"New Orleans-Metairie, LA",22,103,2000-01-31,NaN,0
4,423,274,Caddo Parish,county,LA,LA,"Shreveport-Bossier City, LA",22,17,2000-01-31,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...
65481,3271,1560,West Baton Rouge Parish,county,LA,LA,"Baton Rouge, LA",22,121,2022-10-31,396405.0,5
65482,2808,1577,Morehouse Parish,county,LA,LA,"Monroe, LA",22,67,2022-10-31,165479.0,5
65483,3117,1661,Plaquemines Parish,county,LA,LA,"New Orleans-Metairie, LA",22,75,2022-10-31,532073.0,5
65484,768,1710,Union Parish,county,LA,LA,"Monroe, LA",22,111,2022-10-31,274400.0,5
65485,3127,1760,Saint James Parish,county,LA,LA,"New Orleans-Metairie, LA",22,93,2022-10-31,294840.0,5

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Team 55 [NEW]/Data/zillow_data_update/zillow_single_family_homes.csv")
df

,RegionID,SizeRank,RegionName,RegionType,StateName,State,Metro,StateCodeFIPS,MunicipalCodeFIPS,Date,Value,tier
0,3266,158,East Baton Rouge Parish,county,LA,LA,"Baton Rouge, LA",22,33,2000-01-31,NaN,0.00_0.33
1,2743,160,Jefferson Parish,county,LA,LA,"New Orleans-Metairie, LA",22,51,2000-01-31,99616.0,0.00_0.33
2,1953,178,Orleans Parish,county,LA,LA,"New Orleans-Metairie, LA",22,71,2000-01-31,77439.0,0.00_0.33
3,3225,265,Saint Tammany Parish,county,LA,LA,"New Orleans-Metairie, LA",22,103,2000-01-31,NaN,0.00_0.33
4,423,274,Caddo Parish,county,LA,LA,"Shreveport-Bossier City, LA",22,17,2000-01-31,NaN,0.00_0.33
...,...,...,...,...,...,...,...,...,...,...,...,...
50959,2161,2430,Caldwell Parish,county,LA,LA,NaN,22,21,2022-10-31,185017.0,0.67_1.0
50960,2830,2540,Red River Parish,county,LA,LA,NaN,22,81,2022-10-31,198830.0,0.67_1.0
50961,3160,2661,East Carroll Parish,county,LA,LA,NaN,22,35,2022-10-31,131864.0,0.67_1.0
50962,1583,2679,Cameron Parish,county,LA,LA,"Lake Charles, LA",22,23,2022-10-31,327952.0,0.67_1.0
50963,1428,2855,Tensas Parish,county,LA,LA,NaN,22,107,2022-10-31,498880.0,0.67_1.0