In [9]:
import pandas as pd

import os
import gc


#0-5 bedroom homes time series
#merging the bedroom 0-5 count zhvi smooth into a list
df_list = []

for i in range(6):
  df = pd.read_csv("/content/drive/MyDrive/Team 55 [NEW]/Data/zillow_data_update/county/County_zhvi_bdrmcnt_" + str(i) + "_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv")
  df = df[df["State"] == "LA"]
  df = df.melt(id_vars=["RegionID",	"SizeRank",	"RegionName",	"RegionType",	"StateName",	"State",	"Metro",	"StateCodeFIPS",	"MunicipalCodeFIPS"], var_name="Date", value_name="Value")
  df["bdrmcnt"] = i
  df_list.append(df)
  del(df)
  gc.collect()
  df=pd.DataFrame()

merged_df = pd.concat(df_list)



#merged_df.to_csv('/content/drive/MyDrive/Team 55 [NEW]/Data/zillow_data_update/zillow_bdrmcnt.csv', index=False)  

whe = ["Washington Parish", "Orleans Parish", "St. Bernard Parish", "St. Charles Parish", "Jefferson Parish", "Plaquemines Parish", "St. James Parish", "St. John the Baptist Parish", "St. Tammany Parish", "Tangipahoa Parish", "Ascension Parish", "East Baton Rouge Parish", "East Feliciana Parish", "Iberville Parish", "Livingston Parish", "Pointe Coupee Parish", "St. Helena Parish", "West Baton Rouge Parish", "West Feliciana Parish", "Caddo Parish"]

merged_df [ merged_df["RegionName"] == "Ascension Parish"]

,RegionID,SizeRank,RegionName,RegionType,StateName,State,Metro,StateCodeFIPS,MunicipalCodeFIPS,Date,Value,bdrmcnt
12,2623,514,Ascension Parish,county,LA,LA,"Baton Rouge, LA",22,5,2000-01-31,NaN,2
66,2623,514,Ascension Parish,county,LA,LA,"Baton Rouge, LA",22,5,2000-02-29,NaN,2
120,2623,514,Ascension Parish,county,LA,LA,"Baton Rouge, LA",22,5,2000-03-31,NaN,2
174,2623,514,Ascension Parish,county,LA,LA,"Baton Rouge, LA",22,5,2000-04-30,NaN,2
228,2623,514,Ascension Parish,county,LA,LA,"Baton Rouge, LA",22,5,2000-05-31,NaN,2
...,...,...,...,...,...,...,...,...,...,...,...,...
9965,2623,514,Ascension Parish,county,LA,LA,"Baton Rouge, LA",22,5,2022-06-30,474063.0,5
10002,2623,514,Ascension Parish,county,LA,LA,"Baton Rouge, LA",22,5,2022-07-31,479383.0,5
10039,2623,514,Ascension Parish,county,LA,LA,"Baton Rouge, LA",22,5,2022-08-31,482923.0,5
10076,2623,514,Ascension Parish,county,LA,LA,"Baton Rouge, LA",22,5,2022-09-30,487302.0,5
10113,2623,514,Ascension Parish,county,LA,LA,"Baton Rouge, LA",22,5,2022-10-31,488042.0,5

array(['East Baton Rouge Parish', 'Jefferson Parish', 'Orleans Parish',
       'Saint Tammany Parish', 'Caddo Parish', 'Lafayette Parish',
       'Calcasieu Parish', 'Ouachita Parish', 'Livingston Parish',
       'Tangipahoa Parish', 'Beauregard Parish', 'Rapides Parish',
       'Bossier Parish', 'Terrebonne Parish', 'Lafourche Parish',
       'Morehouse Parish', 'Union Parish', 'Saint James Parish',
       'Cameron Parish', 'Ascension Parish', 'Saint Landry Parish',
       'Iberia Parish', 'Acadia Parish', 'Vermilion Parish',
       'Saint Martin Parish', 'Saint Charles Parish', 'Saint Mary Parish',
       'Vernon Parish', 'Lincoln Parish', 'Washington Parish',
       'Saint Bernard Parish', 'Saint John the Baptist Parish',
       'Avoyelles Parish', 'Webster Parish', 'Natchitoches Parish',
       'Evangeline Parish', 'Iberville Parish', 'Jefferson Davis Parish',
       'De Soto Parish', 'West Baton Rouge Parish', 'Allen Parish',
       'Sabine Parish', 'Plaquemines Parish', 'Assumption Parish',
       'Grant Parish', 'Pointe Coupee Parish', 'Richland Parish',
       'Franklin Parish', 'Concordia Parish', 'East Feliciana Parish',
       'Claiborne Parish', 'Jackson Parish', 'West Feliciana Parish',
       'Bienville Parish', 'LaSalle Parish', 'Winn Parish',
       'West Carroll Parish', 'Saint Helena Parish', 'Caldwell Parish',
       'Red River Parish', 'East Carroll Parish', 'Tensas Parish'],
      dtype=object)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:

#single family homes time series
df_list = []

tiers =["_0.0_0.33_sm_sa_month.csv" ,"_0.33_0.67_sm_sa_month.csv","_0.67_1.0_sm_sa_month.csv" ]

for i in range(3):
  df = pd.read_csv("/content/drive/MyDrive/Team 55 [NEW]/Data/zillow_data_update/county/County_zhvi_uc_sfr_tier" + tiers[i] )
  df = df[df["State"] == "LA"]
  df = df.melt(id_vars=["RegionID",	"SizeRank",	"RegionName",	"RegionType",	"StateName",	"State",	"Metro",	"StateCodeFIPS",	"MunicipalCodeFIPS"], var_name="Date", value_name="Value")
  if i == 0:
    df["tier"] = "0.00_0.33"

  if i == 1:
    df["tier"] = "0.33_0.67"
  
  if i == 2:
    df["tier"] = "0.67_1.0"
  df_list.append(df)
  del(df)
  gc.collect()
  df=pd.DataFrame()

merged_df = pd.concat(df_list)

merged_df.to_csv('/content/drive/MyDrive/Team 55 [NEW]/Data/zillow_data_update/zillow_single_family_homes.csv', index=False)

In [ ]:
#all homes time series
df_list = []

tiers =["_0.0_0.33_sm_sa_month.csv" ,"_0.33_0.67_sm_sa_month.csv","_0.67_1.0_sm_sa_month.csv" ]

for i in range(3):
  df = pd.read_csv("/content/drive/MyDrive/Team 55 [NEW]/Data/zillow_data_update/county/County_zhvi_uc_sfrcondo_tier" + tiers[i] )
  df = df[df["State"] == "LA"]
  df = df.melt(id_vars=["RegionID",	"SizeRank",	"RegionName",	"RegionType",	"StateName",	"State",	"Metro",	"StateCodeFIPS",	"MunicipalCodeFIPS"], var_name="Date", value_name="Value")
  if i == 0:
    df["tier"] = "0.00_0.33"

  if i == 1:
    df["tier"] = "0.33_0.67"
  
  if i == 2:
    df["tier"] = "0.67_1.0"
  df_list.append(df)
  del(df)
  gc.collect()
  df=pd.DataFrame()

merged_df = pd.concat(df_list)

merged_df.to_csv('/content/drive/MyDrive/Team 55 [NEW]/Data/zillow_data_update/zillow_all_homes.csv', index=False)

NameError: ignored

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Team 55 [NEW]/Data/zillow_data_update/zillow_all_homes.csv" )
df

,RegionID,SizeRank,RegionName,RegionType,StateName,State,Metro,StateCodeFIPS,MunicipalCodeFIPS,Date,Value,tier
0,3266,158,East Baton Rouge Parish,county,LA,LA,"Baton Rouge, LA",22,33,2000-01-31,NaN,0.00_0.33
1,2743,160,Jefferson Parish,county,LA,LA,"New Orleans-Metairie, LA",22,51,2000-01-31,96733.0,0.00_0.33
2,1953,178,Orleans Parish,county,LA,LA,"New Orleans-Metairie, LA",22,71,2000-01-31,80356.0,0.00_0.33
3,3225,265,Saint Tammany Parish,county,LA,LA,"New Orleans-Metairie, LA",22,103,2000-01-31,NaN,0.00_0.33
4,423,274,Caddo Parish,county,LA,LA,"Shreveport-Bossier City, LA",22,17,2000-01-31,NaN,0.00_0.33
...,...,...,...,...,...,...,...,...,...,...,...,...
50959,2161,2430,Caldwell Parish,county,LA,LA,NaN,22,21,2022-10-31,185017.0,0.67_1.0
50960,2830,2540,Red River Parish,county,LA,LA,NaN,22,81,2022-10-31,198830.0,0.67_1.0
50961,3160,2661,East Carroll Parish,county,LA,LA,NaN,22,35,2022-10-31,131864.0,0.67_1.0
50962,1583,2679,Cameron Parish,county,LA,LA,"Lake Charles, LA",22,23,2022-10-31,327951.0,0.67_1.0
50963,1428,2855,Tensas Parish,county,LA,LA,NaN,22,107,2022-10-31,498880.0,0.67_1.0

In [ ]:
cols_count = {}

for fle in os.listdir('drive/MyDrive/Team 55 [NEW]/Data/zillow_data_update/county/'):

  if(fle != "CountyCrossWalk_Zillow.csv"):
    cur_file = 'drive/MyDrive/Team 55 [NEW]/Data/zillow_data_update/county/' + fle
    df = pd.read_csv(cur_file)

    cols_count[fle] = len(df.columns.tolist())

    del(df)
    gc.collect()
    df=pd.DataFrame()




pd.DataFrame({"files": cols_count.keys(), "cols_count":cols_count.values() }).sort_values(by = ["cols_count","files"])

                                                files  cols_count
38                                         County.csv           1
39                                           fetch.sh           1
37                           County_zori_sm_month.csv         101
36                        County_zori_sm_sa_month.csv         101
1   County_zhvi_bdrmcnt_0_uc_sfrcondo_tier_0.33_0....         283
4   County_zhvi_bdrmcnt_1_uc_sfrcondo_tier_0.33_0....         283
7   County_zhvi_bdrmcnt_2_uc_sfrcondo_tier_0.33_0....         283
12  County_zhvi_bdrmcnt_3_uc_sfrcondo_tier_0.33_0....         283
11  County_zhvi_bdrmcnt_4_uc_sfrcondo_tier_0.33_0....         283
9   County_zhvi_bdrmcnt_5_uc_sfrcondo_tier_0.33_0....         283
23               County_zhvi_uc_condo_sm_sa_month.csv         283
17  County_zhvi_uc_condo_tier_0.0_0.33_sm_sa_month...         283
18  County_zhvi_uc_condo_tier_0.33_0.67_sm_sa_mont...         283
15  County_zhvi_uc_condo_tier_0.67_1.0_sm_sa_month...         283
21                 County_zhvi_uc_sfr_sm_sa_month.csv         283
22   County_zhvi_uc_sfr_tier_0.0_0.33_sm_sa_month.csv         283
16  County_zhvi_uc_sfr_tier_0.33_0.67_sm_sa_month.csv         283
26   County_zhvi_uc_sfr_tier_0.67_1.0_sm_sa_month.csv         283
25            County_zhvi_uc_sfrcondo_sm_sa_month.csv         283
33  County_zhvi_uc_sfrcondo_tier_0.0_0.33_sm_sa_mo...         283
31  County_zhvi_uc_sfrcondo_tier_0.33_0.67_sm_sa_m...         283
34  County_zhvi_uc_sfrcondo_tier_0.67_1.0_sm_sa_mo...         283
2   County_zhvi_bdrmcnt_0_uc_sfrcondo_tier_0.33_0....         331
0   County_zhvi_bdrmcnt_1_uc_sfrcondo_tier_0.33_0....         331
3   County_zhvi_bdrmcnt_2_uc_sfrcondo_tier_0.33_0....         331
10  County_zhvi_bdrmcnt_3_uc_sfrcondo_tier_0.33_0....         331
5   County_zhvi_bdrmcnt_4_uc_sfrcondo_tier_0.33_0....         331
8   County_zhvi_bdrmcnt_5_uc_sfrcondo_tier_0.33_0....         331
6                      County_zhvi_uc_condo_month.csv         331
19       County_zhvi_uc_condo_tier_0.0_0.33_month.csv         331
14      County_zhvi_uc_condo_tier_0.33_0.67_month.csv         331
13       County_zhvi_uc_condo_tier_0.67_1.0_month.csv         331
20                       County_zhvi_uc_sfr_month.csv         331
28         County_zhvi_uc_sfr_tier_0.0_0.33_month.csv         331
24        County_zhvi_uc_sfr_tier_0.33_0.67_month.csv         331
30         County_zhvi_uc_sfr_tier_0.67_1.0_month.csv         331
27                  County_zhvi_uc_sfrcondo_month.csv         331
29    County_zhvi_uc_sfrcondo_tier_0.0_0.33_month.csv         331
32   County_zhvi_uc_sfrcondo_tier_0.33_0.67_month.csv         331
35    County_zhvi_uc_sfrcondo_tier_0.67_1.0_month.csv         331

In [ ]:
#Legened*  
#the dataframe contains info of the amount of columns in a particular file
#some of the files contains strings such as _0.0_0.33(Bottom tier), _0.33_0.67(Single family homes), and _0.67_1.0(Top tier)
#ZHVI and ZORI values are located with in the date columns for the zillow dataset


#** from Zillow.com below
#Zillow Home Value Index (ZHVI): A smoothed, seasonally adjusted measure of the typical home value and market changes across a given region and housing type.

#Zillow Observed Rent Index (ZORI): A smoothed measure of the typical observed market rate rent across a given region. ZORI is a repeat-rent index that is weighted 
#to the rental housing stock to ensure representativeness across the entire market, not just those homes currently listed for-rent. The index is dollar-denominated 
#by computing the mean of listed rents that fall into the 40th to 60th percentile range for all homes and apartments in a given region, which is once again weighted to reflect
# the rental housing stock.


# Files to merge, they have the same columns                        Columns
# County_zhvi_bdrmcnt_0_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv	283
# County_zhvi_bdrmcnt_1_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv	283
#	County_zhvi_bdrmcnt_2_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv	283
#	County_zhvi_bdrmcnt_3_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv	283
#	County_zhvi_bdrmcnt_4_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv	283
#	County_zhvi_bdrmcnt_5_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv	283


#Files to merge                                       Columns
#County_zhvi_uc_condo_tier_0.0_0.33_sm_sa_month.csv	  283
#County_zhvi_uc_condo_tier_0.33_0.67_sm_sa_month.csv	283
#County_zhvi_uc_condo_tier_0.67_1.0_sm_sa_month.csv	  283


#Files to merge                                       Columns
#County_zhvi_uc_sfr_tier_0.0_0.33_sm_sa_month.csv	283
#County_zhvi_uc_sfr_tier_0.33_0.67_sm_sa_month.csv	283
#County_zhvi_uc_sfr_tier_0.67_1.0_sm_sa_month.csv	283

# SM- smoothed, SA- seaonally adjusted                                    283 COLUMNS                          311 COLUMNS(POSSIBLY NOT USEABLE SINCE THIS DATA IS NOT SMOOTHENED)
#                 COUNTY NAME        COUNTY       STATE             BETWEEN [2000-01-31 TO 2022-10-31] or [1996-01-31 TO 2018-10-31]

#columns in the RegionName TEXT, RegionType TEXT, StateName TEXT,  TIMEDATE (20XX-XX-XX )