In [ ]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure
import os
import gc
#import pingouin
from scipy.stats import chi2_contingency

Mounted at /content/drive

In [ ]:
occupancy_tract_2020 = pd.read_csv("/content/drive/MyDrive/Team 55 [NEW]/Data/Extended Analysis/Housing Occupancy Datasets/nhgis0007_ds248_2020_tract.csv", engine='python', encoding='latin1', skiprows= 1)

occupancy_2020 = occupancy_tract_2020[['GIS Join Match Code',  'Data File Year',  'State Name',  'County Name',  'Census Tract Code', 'Total', 'Occupied', 'Vacant']] 
occupancy_2020 =occupancy_2020[(occupancy_2020['State Name']=='Louisiana')]
occupancy_2020

,GIS Join Match Code,Data File Year,State Name,County Name,Census Tract Code,Total,Occupied,Vacant
32994,G2200010960101,2020,Louisiana,Acadia Parish,960101,1460,1342,118
32995,G2200010960102,2020,Louisiana,Acadia Parish,960102,1058,958,100
32996,G2200010960201,2020,Louisiana,Acadia Parish,960201,1296,1211,85
32997,G2200010960202,2020,Louisiana,Acadia Parish,960202,1014,901,113
32998,G2200010960300,2020,Louisiana,Acadia Parish,960300,1435,1307,128
...,...,...,...,...,...,...,...,...
34377,G2201270960100,2020,Louisiana,Winn Parish,960100,1796,1447,349
34378,G2201270960201,2020,Louisiana,Winn Parish,960201,1210,960,250
34379,G2201270960202,2020,Louisiana,Winn Parish,960202,1032,893,139
34380,G2201270960300,2020,Louisiana,Winn Parish,960300,1260,1020,240
34381,G2201270960400,2020,Louisiana,Winn Parish,960400,1041,861,180

In [ ]:
#Year: 5-Year Data  2011-2015
#The 5-Year Summary File provides estimates of average characteristics from 2011 through 2015.
#Would this be okay to use for 2015?
occupancy_tract_2015 = pd.read_csv("/content/drive/MyDrive/Team 55 [NEW]/Data/Extended Analysis/Housing Occupancy Datasets/nhgis0008_ds215_20155_tract.csv", engine='python', encoding='latin1', skiprows= 1)


occupancy_2015 = occupancy_tract_2015[['GIS Join Match Code',  'Data File Year',  'State Name',  'County Name',  'Census Tract Code', 'Estimates: Total', 'Estimates: Occupied', 'Estimates: Vacant']] 
occupancy_2015 =occupancy_2015[(occupancy_2015['State Name']=='Louisiana')]
occupancy_2015

,GIS Join Match Code,Data File Year,State Name,County Name,Census Tract Code,Estimates: Total,Estimates: Occupied,Estimates: Vacant
28303,G2200010960100,2011-2015,Louisiana,Acadia Parish,960100,2440,2272,168
28304,G2200010960200,2011-2015,Louisiana,Acadia Parish,960200,2494,2214,280
28305,G2200010960300,2011-2015,Louisiana,Acadia Parish,960300,1502,1369,133
28306,G2200010960400,2011-2015,Louisiana,Acadia Parish,960400,2700,2421,279
28307,G2200010960500,2011-2015,Louisiana,Acadia Parish,960500,2547,2312,235
...,...,...,...,...,...,...,...,...
29446,G2201250951800,2011-2015,Louisiana,West Feliciana Parish,951800,2993,2437,556
29447,G2201270960100,2011-2015,Louisiana,Winn Parish,960100,1989,1381,608
29448,G2201270960200,2011-2015,Louisiana,Winn Parish,960200,2575,2041,534
29449,G2201270960300,2011-2015,Louisiana,Winn Parish,960300,1458,1062,396
29450,G2201270960400,2011-2015,Louisiana,Winn Parish,960400,1221,1029,192

In [ ]:
occupancy_tract_2010 = pd.read_csv("/content/drive/MyDrive/Team 55 [NEW]/Data/Extended Analysis/Housing Occupancy Datasets/nhgis0016_ds172_2010_tract.csv", engine='python', encoding='latin1', skiprows= 1)


occupancy_2010 = occupancy_tract_2010[['GIS Join Match Code',  'Data File Year',  'State Name',  'County Name',  'Census Tract Code', 'Total.1', 'Occupied', 'Vacant']] 
occupancy_2010 =occupancy_2010[(occupancy_2010['State Name']=='Louisiana')]
occupancy_2010

,GIS Join Match Code,Data File Year,State Name,County Name,Census Tract Code,Total.1,Occupied,Vacant
28303,G2200010960100,2010,Louisiana,Acadia Parish,960100,2574,2345,229
28304,G2200010960200,2010,Louisiana,Acadia Parish,960200,2362,2144,218
28305,G2200010960300,2010,Louisiana,Acadia Parish,960300,1427,1286,141
28306,G2200010960400,2010,Louisiana,Acadia Parish,960400,2604,2362,242
28307,G2200010960500,2010,Louisiana,Acadia Parish,960500,2349,2178,171
...,...,...,...,...,...,...,...,...
29446,G2201250951800,2010,Louisiana,West Feliciana Parish,951800,2958,2552,406
29447,G2201270960100,2010,Louisiana,Winn Parish,960100,2091,1482,609
29448,G2201270960200,2010,Louisiana,Winn Parish,960200,2571,1871,700
29449,G2201270960300,2010,Louisiana,Winn Parish,960300,1448,1155,293
29450,G2201270960400,2010,Louisiana,Winn Parish,960400,1124,961,163

In [ ]:
#Year: 5-Year Data  2005-2009
#The 5-Year Summary File provides estimates of average characteristics from 2005 through 2009.
#Would this be okay to use for 2005? 
occupancy_tract_2005 = pd.read_csv("/content/drive/MyDrive/Team 55 [NEW]/Data/Extended Analysis/Housing Occupancy Datasets/nhgis0010_ds195_20095_tract.csv", engine='python', encoding='latin1', skiprows= 1)


occupancy_2005 = occupancy_tract_2005[['GIS Join Match Code',  'Data File Year',  'State Name',  'County Name',  'Census Tract Code', 'Estimates: Total', 'Estimates: Occupied', 'Estimates: Vacant']] 
occupancy_2005 =occupancy_2005[(occupancy_2005['State Name']=='Louisiana')]
occupancy_2005

,GIS Join Match Code,Data File Year,State Name,County Name,Census Tract Code,Estimates: Total,Estimates: Occupied,Estimates: Vacant
24533,G2200010960100,2005-2009,Louisiana,Acadia Parish,960100,2859,2613,246
24534,G2200010960200,2005-2009,Louisiana,Acadia Parish,960200,2017,1908,109
24535,G2200010960300,2005-2009,Louisiana,Acadia Parish,960300,1255,1192,63
24536,G2200010960400,2005-2009,Louisiana,Acadia Parish,960400,2363,2016,347
24537,G2200010960500,2005-2009,Louisiana,Acadia Parish,960500,2182,1927,255
...,...,...,...,...,...,...,...,...
25634,G2201250951800,2005-2009,Louisiana,West Feliciana Parish,951800,2924,2565,359
25635,G2201270960100,2005-2009,Louisiana,Winn Parish,960100,2324,1690,634
25636,G2201270960200,2005-2009,Louisiana,Winn Parish,960200,2733,1973,760
25637,G2201270960300,2005-2009,Louisiana,Winn Parish,960300,1595,1181,414
25638,G2201270960400,2005-2009,Louisiana,Winn Parish,960400,1193,960,233

In [ ]:
#Total column looks incorrect --stems from original NHGIS dataset
#New total column can be created by adding Occupied and Vacant columns...
occupancy_tract_2000 = pd.read_csv("/content/drive/MyDrive/Team 55 [NEW]/Data/Extended Analysis/Housing Occupancy Datasets/nhgis0015_ds146_2000_tract.csv", engine='python', encoding='latin1', skiprows= 1)


occupancy_2000 = occupancy_tract_2000[['GIS Join Match Code',  'Data File Year',  'State Name',  'County Name',  'Census Tract Code', 'Total', 'Occupied', 'Vacant']] 
occupancy_2000 =occupancy_2000[(occupancy_2000['State Name']=='Louisiana')]
occupancy_2000

,GIS Join Match Code,Data File Year,State Name,County Name,Census Tract Code,Total,Occupied,Vacant
24517,G2200010960100,2000,Louisiana,Acadia,960100,2236,2236,174
24518,G2200010960200,2000,Louisiana,Acadia,960200,1764,1764,145
24519,G2200010960300,2000,Louisiana,Acadia,960300,1145,1145,101
24520,G2200010960400,2000,Louisiana,Acadia,960400,1991,1991,185
24521,G2200010960500,2000,Louisiana,Acadia,960500,1692,1692,104
...,...,...,...,...,...,...,...,...
25618,G2201250951800,2000,Louisiana,West Feliciana,951800,2296,2296,325
25619,G2201270960100,2000,Louisiana,Winn,960100,1592,1592,563
25620,G2201270960200,2000,Louisiana,Winn,960200,1984,1984,596
25621,G2201270960300,2000,Louisiana,Winn,960300,1328,1328,247
25622,G2201270960400,2000,Louisiana,Winn,960400,1026,1026,166

In [3]:
df = pd.read_csv('/content/drive/MyDrive/Team 55/Team 55 [NEW]/Data/Extended Analysis/Population (including by race ethnicity) by City/la00001.uf1', engine='python', encoding='latin1')

EmptyDataError: ignored